// <auto-generated />
namespace GolfApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Ohsomuch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ohsomuch));
        
        string IMigrationMetadata.Id
        {
            get { return "201803120939007_Oh so much"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
